apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.svc.webshoppingapigw }}
  labels:
    app: {{ template "apigwws.name" . }}
    chart: {{ template "apigwws.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "true" #Enable scraping for this pod 
    prometheus.io/scheme: "http" #If the metrics endpoint is secured then you will need to set this to `https`, if not default ‘http’
    prometheus.io/path: "/stats/prometheus" #If the metrics path is not /metrics, define it with this annotation. 
    prometheus.io/port: "8001" #If port is not 9102 use this annotation
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    app: {{ template "apigwws.name" . }}
    release: {{ .Release.Name }}
